### ISSUE TITLE
should be better about style for ebean.io??

### ISSUE THREAD

**Issue by sizer** [ebean-orm/website-source#32]
I think ebean.io is worthy, but ugly alitte about css... :thinking: 
Especially, when access from mobile...

![ebean io_(iPhone 5_SE)](https://user-images.githubusercontent.com/7848879/56468324-d2a4c900-6465-11e9-9a4f-a9ee468c0b36.png)

**Comment by rbygrave** [comment]
Can close this now with merged PR.  Ta.
