### ISSUE TITLE
references to findFutureRowCount should be change findFutureCount 

### ISSUE THREAD

**Issue by coder007** [ebean-orm/website-source#43]
references to findFutureRowCount should be change findFutureCount 

this is still showing up in the latest version of the documentation - https://ebean.io/docs/query/findPagedList

![image](https://user-images.githubusercontent.com/1185589/90035892-8f223e00-dcec-11ea-8024-1e47175c6788.png)

https://github.com/ebean-orm/website-source/blob/7b7b2c328cb382f104f644bad4aea2081d35a316/docs/query/findPagedList.html#L26

as the method has now been changed to findFutureCount
https://github.com/ebean-orm/ebean/issues/826

this also happens in couple of other places
https://github.com/ebean-orm/website-source/search?q=findFutureRowCount&unscoped_q=findFutureRowCount

**Comment by rbygrave** [comment]
Great, thanks !!  Fixed now.
