### ISSUE TITLE
How to Contribute to Documentation

### ISSUE THREAD

**Issue by risenhoover** [ebean-orm/website-source#49]
I have added some helpful notes to the documentation but I do not seem to have the permissions required to push a branch. Any thoughts on this?

**Comment by rbygrave** [comment]
Typically create a fork, push to that, then create a PR from that branch to
master.

That should do the trick.

Cheers, Rob.

**Comment by risenhoover** [comment]
Ah, the fork. Missed the fork.

**Comment by risenhoover** [comment]
PR Submitted.
